name: tads
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  provider: ^6.1.5
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_dotenv: ^6.0.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  flutter_tts: 3.8.5
  
  path_provider: ^2.0.11
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - .env
    - assets/local_db.json
    - assets/dashboard_data.json
    - assets/students_db.json
    - assets/analysis_data.json
    - assets/fonts/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
